import { mkdirSync, writeFileSync } from 'node:fs';
import { buildRegistry } from '../../src/content/loader.js';
import { readContentFromDisk } from '../content/io.js';

/**
 * Generates TypeScript from the content data.
 *
 * Two outputs, for two different jobs:
 *
 *  - `ids.ts` gives every content id a union type, so the editor autocompletes
 *    them and the compiler rejects an invented one.
 *  - `references.ts` re-states every cross-file reference as a typed array. A
 *    wave naming "husk_typo" becomes a type error at that assignment, which is
 *    what turns a content typo into a build failure instead of a crash on wave
 *    nine. content-lint catches the same thing with a friendlier message; this
 *    catches it without anyone remembering to run the linter.
 */

const OUT_DIR = 'src/content/generated';

const header = (what: string) =>
  `/* GENERATED by tools/content-gen — do not edit.\n * ${what}\n * Run \`npm run content:gen\` after changing anything in src/content/data.\n */\n\n`;

function unionOf(ids: readonly string[]): string {
  return ids.length === 0 ? 'never' : ids.map((id) => `'${id}'`).join(' | ');
}

function idBlock(typeName: string, constName: string, ids: readonly string[]): string {
  const sorted = [...ids].sort();
  return (
    `export type ${typeName} = ${unionOf(sorted)};\n\n` +
    `export const ${constName} = [${sorted.map((i) => `'${i}'`).join(', ')}] as const;\n\n`
  );
}

function refBlock(
  constName: string,
  typeName: string,
  refs: readonly string[],
  note: string,
): string {
  const unique = [...new Set(refs)].sort();
  return (
    `/** ${note} */\nexport const ${constName}: readonly ${typeName}[] = [\n` +
    unique.map((r) => `  '${r}',`).join('\n') +
    (unique.length > 0 ? '\n' : '') +
    '];\n\n'
  );
}

const registry = buildRegistry(readContentFromDisk());
mkdirSync(OUT_DIR, { recursive: true });

/* ---- ids.ts ---- */
let ids = header('Union types for every content id.');
ids += idBlock('TowerId', 'TOWER_IDS', [...registry.towers.keys()]);
ids += idBlock('EnemyId', 'ENEMY_IDS', [...registry.enemies.keys()]);
ids += idBlock('StageId', 'STAGE_IDS', [...registry.stages.keys()]);
ids += idBlock('PowerId', 'POWER_IDS', [...registry.powers.keys()]);
ids += idBlock('HeroId', 'HERO_IDS', [...registry.heroes.keys()]);
ids += idBlock('TalentId', 'TALENT_IDS', [...registry.talents.keys()]);
ids += idBlock('ReactionId', 'REACTION_IDS', [...registry.reactions.keys()]);
ids += idBlock(
  'SpecialisationId',
  'SPECIALISATION_IDS',
  [...registry.towers.values()].flatMap((t) => t.specialisations.map((s) => s.id)),
);
writeFileSync(`${OUT_DIR}/ids.ts`, ids);

/* ---- references.ts ---- */
const waveEnemies = [...registry.stages.values()].flatMap((s) =>
  s.waves.flatMap((w) => w.groups.map((g) => g.enemy)),
);
const unlockStages = [
  ...[...registry.towers.values()].map((t) => t.unlockedByStage),
  ...[...registry.powers.values()].map((p) => p.unlockedByStage),
  ...[...registry.heroes.values()].map((h) => h.unlockedByStage),
].filter((s): s is string => s !== undefined);
const talentRequires = [...registry.talents.values()].flatMap((t) => t.requires);
const derivedEnemies = [...registry.enemies.values()].flatMap((e) =>
  [e.traitConfig.splitsInto, e.traitConfig.spawns].filter((v): v is string => v !== undefined),
);

let refs = header('Cross-file references, typed so a bad id fails to compile.');
refs += `import type { EnemyId, StageId, TalentId } from './ids.js';\n\n`;
refs += refBlock('WAVE_ENEMY_REFS', 'EnemyId', waveEnemies, 'Enemies named by stage waves.');
refs += refBlock('UNLOCK_STAGE_REFS', 'StageId', unlockStages, 'Stages named by unlock gates.');
refs += refBlock(
  'TALENT_REQUIRE_REFS',
  'TalentId',
  talentRequires,
  'Talents named as prerequisites.',
);
refs += refBlock(
  'DERIVED_ENEMY_REFS',
  'EnemyId',
  derivedEnemies,
  'Enemies produced by splitting or spawning.',
);
writeFileSync(`${OUT_DIR}/references.ts`, refs);

const counts = [
  `${registry.towers.size} towers`,
  `${registry.enemies.size} enemies`,
  `${registry.stages.size} stages`,
  `${registry.powers.size} powers`,
  `${registry.heroes.size} heroes`,
  `${registry.talents.size} talents`,
  `${registry.statuses.size} statuses`,
  `${registry.reactions.size} reactions`,
];
console.log(`content:gen — ${counts.join(', ')}`);
