/**
 * Generates CHANGELOG.md from Conventional Commit history.
 *
 * This is hand-rolled rather than using conventional-changelog-cli, which at
 * the time of writing ships a writer incompatible with its own presets
 * (conventional-changelog-cli@5 loads writer@8, every preset requires @9) and
 * fails on whichever preset you give it. Parsing is safe to do ourselves
 * because commitlint already guarantees the format in CI.
 *
 * Usage:
 *   node tools/changelog/index.js            # since the last tag
 *   node tools/changelog/index.js --all      # entire history
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const REPO = 'https://github.com/satautiv/tower-defence';

/* Ordered: what a reader cares about most comes first. Types absent from this
   map (chore, ci, build, test) are deliberately not published — real work, but
   not news to someone reading a changelog. */
const SECTIONS = new Map([
  ['feat', 'Features'],
  ['fix', 'Bug fixes'],
  ['perf', 'Performance'],
  ['refactor', 'Refactoring'],
  ['docs', 'Documentation'],
  ['revert', 'Reverts'],
]);

const git = (...args) => execFileSync('git', args, { encoding: 'utf8' }).trim();

function lastTag() {
  try {
    return git('describe', '--tags', '--abbrev=0');
  } catch {
    return null;
  }
}

const all = process.argv.includes('--all');
const since = all ? null : lastTag();
const range = since ? `${since}..HEAD` : 'HEAD';

/* Unit separator: git emits it via %x1f, and it cannot appear in a subject. */
const SEP = String.fromCharCode(31);
const raw = git('log', range, '--format=%h%x1f%s%x1f%H');
const commits = raw ? raw.split('\n') : [];

/** `type(scope)!: subject` — the shape commitlint enforces. */
const HEADER = /^(?<type>\w+)(?:\((?<scope>[^)]+)\))?(?<breaking>!)?: (?<subject>.+)$/;

const grouped = new Map();
const breaking = [];

for (const line of commits) {
  const [short, subject, full] = line.split(SEP);
  if (!short || !subject || !full) continue;

  const m = HEADER.exec(subject);
  if (!m?.groups) continue; // pre-convention commits, e.g. the initial one

  const { type, scope, breaking: bang, subject: text } = m.groups;
  const entry = {
    text: scope ? `**${scope}:** ${text}` : text,
    link: `([${short}](${REPO}/commit/${full}))`,
  };

  if (bang) breaking.push(entry);
  if (!SECTIONS.has(type)) continue;
  if (!grouped.has(type)) grouped.set(type, []);
  grouped.get(type).push(entry);
}

const out = [
  '# Changelog',
  '',
  '<!-- Generated by tools/changelog. Run `npm run changelog`; do not edit by hand. -->',
  '',
  `## ${since ? `Unreleased (since ${since})` : 'Unreleased'}`,
  '',
];

if (breaking.length > 0) {
  out.push('### Breaking changes', '');
  for (const e of breaking) out.push(`- ${e.text} ${e.link}`);
  out.push('');
}

let published = 0;
for (const [type, heading] of SECTIONS) {
  const entries = grouped.get(type);
  if (!entries?.length) continue;
  published += entries.length;
  out.push(`### ${heading}`, '');
  for (const e of entries) out.push(`- ${e.text} ${e.link}`);
  out.push('');
}

if (published === 0) out.push('_No user-facing changes._', '');

writeFileSync('CHANGELOG.md', out.join('\n'));
console.log(`CHANGELOG.md — ${published} entr${published === 1 ? 'y' : 'ies'} from ${range}`);
